version: '3'
services:
  database: 
    image: 'apache/couchdb:2.1'
    container_name: database
    ports:
      - '5984:5984'
    volumes:
      - ./database/db:/opt/couchdb/data
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: server.dockerfile
    volumes:
      - ./server:/usr/src/app
    ports:
      - '3000:3000'
    links:
      - database
    depends_on:
      - database