version: '3'
services:
  database: 
    image: 'couchdb:2.1'
    container_name: database
    build:
      context: ./database
      dockerfile: database.dockerfile
    ports:
      - '5984:5984'
    networks: 
      - main-network
    volumes:
      - ./database/db:/opt/couchdb/data
      # - ./database/config:/opt/couchdb/etc

  nginx:
    build:
        dockerfile: web.dockerfile
        context: ./web
    image: nginx
    container_name: nginx
    volumes:
      - ./web:/var/www/public
    ports:
        - "80:80"
    networks: 
        - main-network
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: server.dockerfile
    volumes:
      - ./server:/usr/src/app
    links:
      - database
    ports:
      - '3000:3000'
    networks: 
      - main-network
    depends_on:
      - database
networks:
  main-network:
    driver: bridge